version: 2
updates:
  - package-ecosystem: "pnpm" 
    directory: "/" 
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 5
    rebase-strategy: "auto" 
    labels:
      - "dependencies" 

  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dev-dependencies"
